name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build and push backend image
        run: |
          docker build -t my-backend:latest ./backend
          docker tag my-backend:latest $DOCKER_USERNAME/my-backend:latest
          docker push $DOCKER_USERNAME/my-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t my-frontend:latest ./frontend
          docker tag my-frontend:latest $DOCKER_USERNAME/my-frontend:latest
          docker push $DOCKER_USERNAME/my-frontend:latest

      - name: Configure kubeconfig
        run: |
          echo "$KUBE_CONFIG" | base64 --decode > $HOME/.kube/config

      - name: Apply Kubernetes namespace
        run: kubectl apply -f ./kubernetes/namespace.yaml

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f ./kubernetes/backend.yaml
          kubectl apply -f ./kubernetes/frontend.yaml
